### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by jouathen** [vongola12324/BiPin#2]
<addr>06-24 17:44:34.276  19263-19422/BiPin.own.uat D/BiPin﹕ 開始更新資料褲......
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ java.io.FileNotFoundException: /storage/emulated/0/BiPin/BiPin.db: open failed: ENOENT (No such file or directory)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:456)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at ivye.bipin.util.DownloadUtil.downFile(DownloadUtil.java:79)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at ivye.bipin.database.UpdateHelper.getUpdate(UpdateHelper.java:193)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at ivye.bipin.database.UpdateHelper$1.run(UpdateHelper.java:100)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at libcore.io.Posix.open(Native Method)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:442)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ ... 6 more
06-24 17:44:34.286  19263-19422/BiPin.own.uat E/BiPin﹕ Exception while getting FileInputStream
    java.io.FileNotFoundException: /storage/emulated/0/BiPin/BiPin.db: open failed: ENOENT (No such file or directory)
            at libcore.io.IoBridge.open(IoBridge.java:456)
            at java.io.FileInputStream.<init>(FileInputStream.java:76)
            at ivye.bipin.database.UpdateHelper$1.run(UpdateHelper.java:116)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
            at libcore.io.IoBridge.open(IoBridge.java:442)
            at java.io.FileInputStream.<init>(FileInputStream.java:76)
            at ivye.bipin.database.UpdateHelper$1.run(UpdateHelper.java:116)
            at java.lang.Thread.run(Thread.java:818)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ java.io.FileNotFoundException: /storage/emulated/0/BiPin/BiPin.db: open failed: ENOENT (No such file or directory)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:456)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at java.io.FileInputStream.<init>(FileInputStream.java:76)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at ivye.bipin.database.UpdateHelper$1.run(UpdateHelper.java:116)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at libcore.io.Posix.open(Native Method)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:442)
06-24 17:44:34.286  19263-19422/BiPin.own.uat W/System.err﹕ ... 3 more
06-24 17:44:34.286  19263-19422/BiPin.own.uat E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-16099
    Process: BiPin.own.uat, PID: 19263
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
            at ivye.bipin.database.UpdateHelper$1.run(UpdateHelper.java:140)
            at java.lang.Thread.run(Thread.java:818)
</addr>

**Comment by vongola12324** [comment]
Is this the error message from Android Studio or Eclipse?
And what action you did that cause the app crash?


Victor

**Comment by jouathen** [comment]
1.Android Studio 
2.app crash on launch

**Comment by vongola12324** [comment]
Crash on launch? 
Ummm..... That's strange.
Because I have the app in my OnePlus One (/w Android 5.0.2), it won't crash on launch.
Also, that problem cause by the remote server's problem, I had a special handling about it, so it should not crash......

In summary, thanks for your report, I will check what causing this problem ASAP.

Vongola
